config/routes.rb
Rails.application.routes.draw do

  get 'comments/show'

  get 'comments/new'

  get 'comments/create'

  get 'searches/search'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "users#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :user_images

    resources :searches
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, ImageUploader
  has_many :user_images
  has_many :friendships
  has_many :searches
  has_many :comments

  validates :name, presence: true, length: { minimum: 3 }
  validates :patronymic, presence: true, length: { minimum: 3 }
  validates :surname, presence: true, length: { minimum: 3 }
  validates :username, presence: true, length: { minimum: 3 }
  validates :image, presence: true
end

app/models/user_image.rb
class UserImage < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    attributes = [:name, :patronymic, :surname, :username, :email, :image]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def show
    comment_find
  end

  def new
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @comment = @user.comments.new(comment_params)
    if @comment.save
      redirect_to @user
    else 
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:authors,:description)
  end

  def comment_find
    @comment = Comment.find(params[:id])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def show
  end

  def new
  end

  def create
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!
  
  def search
    @user = User.find(params[:user_id])
    @search = @user.searches.new(search_params)
    if @search.save
      redirect_to @user
    else
      render :new
    end
  end

  private

  def search_params
    params.require(:search).permit(:query)
  end

end

app/controllers/user_images_controller.rb
class UserImagesController < ApplicationController
  
  def show
    user_image_find
  end

  def new
    @user_image = UserImage.new
  end

  def create
    @user_image = UserImage.new(user_image_params)
    if @user_image.save
      redirect_to @user_image
    else
      render :new
    end
  end

  def delete
    user_image_find
    @user_image.destroy!
    redirect_to @user
  end


  private

  def user_image_params
    params.require(:user_image).permit(:description, :image, :user_id)
  end

  def user_image_find
    @user_image = UserImage.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    user_find
  end

  private 
  
  def user_find
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/user_images_helper.rb
module UserImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/new.html.erb
<h1>Friendships#new</h1>
<p>Find me in app/views/friendships/new.html.erb</p>

app/views/friendships/show.html.erb
<h1>Friendships#show</h1>
<p>Find me in app/views/friendships/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>
    <%= csrf_meta_tags %>

     <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      Hello <%= current_user.username %> | <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, data: { confirm: 'Вы уверенны что хотите выйти?' } %>
    <% else %>
      <%= link_to 'Sign In', new_user_session_path %>
    <% end %> |

    <%= link_to 'Главная', root_path %> |
    <%= link_to 'Новая Галлерея', new_user_image_path %>

		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/searches/search.html.erb
<h1>Searches#search</h1>
<p>Find me in app/views/searches/search.html.erb</p>

app/views/user_images/_form_for.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<%= form_for @user_image do |f| %>
        
        <div class="col-md-12">
        	<%= f.label :description, "Описание:" %> <br>
        	<%= f.text_field :description %>
        </div>
			
        <div class="col-md-12">
        	<%= f.label :image, "Картинка:" %><br>
        	<%= f.file_field :image %><br>
        </div>

        <div class="col-md-12">
        	<%= f.button 'Create', submit: '', class: 'btn btn-success' %>
        </div>

			<% end %>
		</div>
	</div>
</div>

app/views/user_images/create.html.erb
<h1>UserImages#create</h1>
<p>Find me in app/views/user_images/create.html.erb</p>

app/views/user_images/delete.html.erb
<h1>UserImages#delete</h1>
<p>Find me in app/views/user_images/delete.html.erb</p>

app/views/user_images/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1 class="color_header text-center">
				Create Gallery
			</h1>
		</div>
		<%= render 'form_for' %>
	</div>
</div>

app/views/user_images/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h1>
			  Gallery
			</h1>
		</div>

		<div class="col-md-4">
			<% @user_images.each do |user_element| %>
				<p>
					<%= user_element.description %>
				</p>

				<p>
					<%= image_tag(user_element.image.url(:medium), alt: 'Image') unless user_element.image.blank? %>
				</p>
			<% end %>
		</div>

	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
			
			<div class="col-md-12">
				<h1 class="color_header text-center">
					Моя Страница
				</h1><br>
			</div>

			<div class="navbar navbar-right col-md-5">
				<%= form_tag(controller: "searches", action: "search", method: "get", class: "nifty_form") do  %>
					<%= text_field_tag(:user)  %>
					<%= submit_tag("Поиск",class: "btn btn-success") %>
				<% end %>	
			</div>
			
			<div class="col-md-12">
				
				<p class="image_alignment img-circle">
					<%= image_tag(@user.image.url(:thumb), alt: 'Avatar_Image') if @user.image? %>		
				</p>

				<h3 class="color_header">
					<%= @user.patronymic %>
					<%= @user.name %>
				</h3>

				<p class="link_alignment">
					<%= link_to 'Изменить', edit_user_registration_path, class: "btn btn-success" %>
				</p>

			</div>

			<div class="col-md-12">
				
				<h2 class="color_header">
					Галлерея
				</h2>

				<% @user.user_images.each do |user_element| %>
					<p>
						<%= image_tag(user_element.image.url(:medium), alt: 'Image') unless user_element.image.blank? %><br>
						<%= user_element.description %>	
					</p>
				<% end %>

			</div>

			<div class="col-md-12">
				
				<h2 class="color_header" >
					Друзі		
				</h2>
				
			
			</div>

	
	</div>
</div>